# Generated by Django 3.0.3 on 2020-11-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_code', models.CharField(max_length=10)),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
